executionName: "execution_1"

username: "root"

servers:
    - host: "ip1"
      port: 5005
      id: 1
    - host: "ip2"
      port: 5005
      id: 2
    - host: "ip3"
      port: 5005
      id: 3
    - host: "ip4"
      port: 5005
      id: 4
    - host: "ip5"
      port: 5005
      id: 5

clients:
  - operations: [read]
    connectToOne: true
  - operations: [read, write, sync_read, CAS, reconfig]
    connectToOne: true
  - operations: [write]
    connectToOne: true
  - operations: [read, write]
    connectToOne: false

totalOperationsPerClient: 10000

partitionEveryInSeconds: 3
partitionDurationInSeconds: 2

